NWN.FinalFantasy.Web/Models/ErrorViewModel.cs
using System;

namespace NWN.FinalFantasy.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NWN.FinalFantasy.Web/Controllers/DownloadController.cs
using Microsoft.AspNetCore.Mvc;

namespace NWN.FinalFantasy.Web.Controllers
{
    public class DownloadController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult DownloadHaks()
        {
            // Could live in a DB or something, but don't want to complicate it.
            const string LocalPath = "/var/www/ffo_public_files/FFOHaks.rar";
            const string ContentType = "application/octet-stream";
            const string FileName = "FFODevelopmentHaks.rar";

            if (!System.IO.File.Exists(LocalPath))
            {
                return Content("Could not find file.");
            }

            return File(System.IO.File.OpenRead(LocalPath), ContentType, FileName);
        }
    }
}

NWN.FinalFantasy.Web/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NWN.FinalFantasy.Web.Controllers
{
    public class GalleryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NWN.FinalFantasy.Web/Controllers/GameplayController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NWN.FinalFantasy.Web.Controllers
{
    public class GameplayController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NWN.FinalFantasy.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NWN.FinalFantasy.Web.Models;

namespace NWN.FinalFantasy.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NWN.FinalFantasy.Web/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace NWN.FinalFantasy.Web.Controllers
{
    public class StoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

NWN.FinalFantasy.Web/Views/Download/Index.cshtml
@{
    ViewData["Title"] = "Downloads";
}

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Downloads</h5>
                <p class="card-text">
                    Players can simply connect to the server and download the necessary files to begin playing.
                    <br />
                    <br />
                    If you are interested in helping us build the server, you can download the required files below. Again - you only need these if you're building. Players don't need them.
                </p>
            </div>
        </div>
    </div>
</div>


<table class="table">
    <thead>
        <tr>
            <th scope="col">File Name</th>
            <th scope="col">Description</th>
            <th scope="col">Instructions</th>
            <th scope="col">Download</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Hakpaks</td>
            <td>These are the DEVELOPMENT-ONLY hakpaks. If you only want to play, you DO NOT need these. Simply connect to the server to get the files and start playing.</td>
            <td>Extract all .hak files to your My Documents/Neverwinter Nights/hak directory. Extract the ffo.tlk to your tlk directory. Make the tlk directory if it doesn't exist already.</td>
            <td>
                <a class="btn btn-primary btn-block" target="_blank" asp-controller="Download" asp-action="DownloadHaks">Download</a>
            </td>
        </tr>
    </tbody>
</table>

NWN.FinalFantasy.Web/Views/Gallery/Index.cshtml
@{
}

<div id="gallerySlides" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#gallerySlides" data-slide-to="0" class="active"></li>
        <li data-target="#gallerySlides" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="img/BalambExterior.png" class="d-block w-100" alt="...">
        </div>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item">
            <img src="img/BalambExterior.png" class="d-block w-100" alt="...">
        </div>
    </div>

    <a class="carousel-control-prev" href="#gallerySlides" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#gallerySlides" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

NWN.FinalFantasy.Web/Views/Gameplay/Index.cshtml
@{
}

NWN.FinalFantasy.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4 font-weight-bold">Final Fantasy 8: Online</h1>
    <h4 class="font-weight-bold">A Neverwinter Nights Persistent World</h4>
</div>

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title font-weight-bold">About the Server</h5>
                <p class="card-text">
                    Final Fantasy 8: Hortus Memoria is a mod built for Neverwinter Nights. Taking place a hundred years after the events of the original game, you are a SeeD candidate at an elite military school called Balamb Garden.
                    <br />
                    <br />
                    Create your character, learn new skills, fight daring battles, and immerse yourself in the world of Final Fantasy 8!
                </p>
            </div>
        </div>
    </div>
</div>

<div class="row">&nbsp;</div>

<div class="row">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Connection Info</h5>
                <p class="card-text">

                    <ul>
                        <li>
                            <b>Direct Connect:</b> play.ff8.io:5121  (Server is currently in development and not accessible at this time)
                        </li>
                        <li>
                            <b>Discord:</b> <a href="https://discord.gg/eF9XxBb">Click Here</a>
                        </li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title font-weight-bold">Buy Neverwinter Nights</h5>
                <p class="card-text">
                    <ul>
                        <li>
                            <b>Buy on Steam:</b> <a href="http://store.steampowered.com/app/704450/Neverwinter_Nights_Enhanced_Edition/" target="_blank">Click Here</a>
                        </li>
                        <li>
                            <b>Buy on Beamdog:</b> <a href="https://www.beamdog.com/products/neverwinter-nights-enhanced-edition#signup-form" target="_blank">Click Here</a>
                        </li>
                        <li>
                            <b>Buy on GOG:</b> <a href="https://www.gog.com/game/neverwinter_nights_enhanced_edition_pack" target="_blank">Click Here</a>
                        </li>
                    </ul>
                </p>
            </div>
        </div>
    </div>
</div>

NWN.FinalFantasy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final Fantasy 8: Hortus Memoria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gallery" asp-action="Index">Gallery</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Download" asp-action="Index">Downloads</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Story" asp-action="Index">Story</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gameplay" asp-action="Index">Gameplay</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://forum.ff8.io/">Forums</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://discord.gg/eF9XxBb" target="_blank">Discord</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://wiki.ff8.io/">Wiki</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href="https://github.com/zunath/NWN.FinalFantasy" target="_blank">Source Code</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container page-holder bg-cover">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">

            Final Fantasy is property of Square Enix. Please don't sue us.

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NWN.FinalFantasy.Web/Views/Story/Index.cshtml
@{
}